# Generated by Django 5.1.2 on 2024-10-23 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
