# Generated by Django 5.1.2 on 2024-10-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field', models.TextField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='video',
        ),
    ]
